// ===== 分別ガイド（見て分かる版・多言語）=====
// 「出す場所」を軸に、各区分の定義・出せるもの・ルールを整理。
// desc/items/rules は {ja,en,pt,easy}。無い言語は ja にフォールバック。

const PLACES = {
  station: { icon:"🗑️", color:"#5b6470",
    label:{ja:"分別ごみステーション", en:"Sorted-waste station", pt:"Estação de lixo", easy:"ごみ ステーション"},
    note:{ja:"収集日に、地区の集積所へ", en:"To your local spot on the collection day", pt:"No ponto local no dia da coleta", easy:"あつめる ひ に ちくの ばしょへ"} },
  shigen: { icon:"♻️", color:"#2f9e6e",
    label:{ja:"資源ステーション", en:"Resource station", pt:"Estação de recursos", easy:"しげん ステーション"},
    note:{ja:"資源の日に。有害・危険ごみもここ", en:"On resource day; also hazardous items", pt:"No dia de recursos; e perigosos", easy:"しげんの ひ に。あぶない ものも ここ"} },
  recycle: { icon:"📦", color:"#3a7cc0",
    label:{ja:"リサイクルステーション（常設拠点）", en:"Recycling station (drop-off)", pt:"Estação de reciclagem (ponto fixo)", easy:"リサイクル ステーション（いつでも）"},
    note:{ja:"古紙・古布等を持込。年中無休 10:00〜18:00（年末年始除く）", en:"Drop off paper/cloth. Daily 10:00–18:00", pt:"Leve papel/tecido. Diário 10h–18h", easy:"かみ・ぬのを もっていく。まいにち 10〜18じ"} },
  apply: { icon:"📞", color:"#7c5cbf",
    label:{ja:"粗大ごみ（申込制）", en:"Oversized (by request)", pt:"Volumoso (sob pedido)", easy:"そだい ごみ（もうしこみ）"},
    note:{ja:"事前申込・処理券が必要", en:"Requires prior request and a fee sticker", pt:"Requer pedido e selo", easy:"さきに もうしこみ・けんが いる"} },
  none: { icon:"⚠️", color:"#c0563a",
    label:{ja:"市では収集しない", en:"Not collected by city", pt:"Não coletado pela cidade", easy:"しやくしょは あつめない"},
    note:{ja:"販売店・メーカー・専門処理へ", en:"Take to retailer/maker/specialist", pt:"Leve à loja/fabricante", easy:"おみせ・メーカーへ"} },
};

const KEY_RULE = {
  ja:"迷ったら大きさで判断：市の指定袋に入れば通常収集、入らない大きさは『粗大ごみ』（申込制・長さ4mまで）。",
  en:"Rule of thumb: if it fits the city bag it's normal waste; if not, it's oversized (by request, up to 4 m).",
  pt:"Regra: se cabe na sacola oficial é lixo normal; se não, é volumoso (sob pedido, até 4 m).",
  easy:"おおきさで きめる：ふくろに はいれば ふつう、はいらなければ そだいごみ。",
};

const GUIDE = [
  { cat:"moyasu", place:"station",
    desc:{ja:"生ごみ・紙くず・布・製品プラなど。指定袋に入る大きさ。",
      en:"Food waste, paper, cloth, product plastics, etc. Must fit in the city bag.",
      pt:"Restos de comida, papel, tecido, plásticos de produtos. Deve caber na sacola.",
      easy:"なまごみ・かみ・ぬの・プラせいひん など。ふくろに はいる おおきさ。"},
    items:{ja:["生ごみ","紙くず","布類","革・ゴム製品","製品プラスチック（容器包装以外）","紙おむつ（汚物除く）"],
      en:["Food waste","Paper scraps","Cloth","Leather/rubber","Product plastics","Diapers (waste removed)"],
      pt:["Restos de comida","Papéis","Tecidos","Couro/borracha","Plásticos de produtos","Fraldas (sem dejetos)"],
      easy:["なまごみ","かみくず","ぬの","かわ・ゴム","プラせいひん","かみおむつ"]},
    rules:{ja:["指定袋に入れて収集日の朝8:30までに","長い枝などは束ねる・切って袋に入る大きさに","指定袋に入らない大きさは粗大ごみ"],
      en:["Put in the city bag by 8:30 AM on collection day","Bundle/cut long branches to fit the bag","If it doesn't fit the bag, it's oversized waste"],
      pt:["Na sacola oficial até 8h30 no dia da coleta","Amarre/corte galhos para caber na sacola","Se não cabe na sacola, é volumoso"],
      easy:["ふくろに いれて あさ 8じ30ぷん までに","ながい えだは たばねる・きる","はいらない ものは そだいごみ"]} },

  { cat:"plastic", place:"station",
    desc:{ja:"プラマークの付いた容器・包装。中身を軽くすすぐ。",
      en:"Containers/packaging with the plastic mark. Rinse lightly.",
      pt:"Embalagens com o símbolo de plástico. Enxágue levemente.",
      easy:"プラマークの ようき・つつみ。かるく あらう。"},
    items:{ja:["食品トレイ","レジ袋","菓子袋","ボトルのフタ・ラベル","発泡スチロール"],
      en:["Food trays","Shopping bags","Snack bags","Caps/labels","Styrofoam"],
      pt:["Bandejas","Sacolas plásticas","Embalagens de doces","Tampas/rótulos","Isopor"],
      easy:["トレイ","レジぶくろ","おかしの ふくろ","ふた・ラベル","はっぽうスチロール"]},
    rules:{ja:["汚れが落ちないものは燃やすごみへ","おもちゃ等の“製品プラ”は燃やすごみ"],
      en:["If dirt won't come off, put in burnable","Product plastics (toys) go to burnable"],
      pt:["Se a sujeira não sai, vai para queimável","Plásticos de produtos (brinquedos) → queimável"],
      easy:["よごれが とれない ものは もやすごみ","おもちゃの プラは もやすごみ"]} },

  { cat:"shigen", place:"shigen",
    desc:{ja:"缶・びん・ペットボトルと、有害・危険ごみ。資源の日に資源ステーションへ。",
      en:"Cans, bottles, PET, plus hazardous items. To the resource station on resource day.",
      pt:"Latas, garrafas, PET e itens perigosos. À estação de recursos no dia de recursos.",
      easy:"かん・びん・ペットボトルと、あぶない ごみ。しげんの ひ に しげんステーションへ。"},
    items:{ja:["飲料缶","ガラスびん","ペットボトル","乾電池・蛍光管（有害）","スプレー缶・ライター（危険）"],
      en:["Beverage cans","Glass bottles","PET bottles","Batteries/tubes (hazardous)","Sprays/lighters (dangerous)"],
      pt:["Latas de bebida","Garrafas de vidro","Garrafas PET","Pilhas/lâmpadas (perigoso)","Sprays/isqueiros (perigoso)"],
      easy:["かん","びん","ペットボトル","でんち・けいこうかん","スプレー・ライター"]},
    rules:{ja:["有害・危険ごみは資源ステーションへ","スプレー缶は使い切る／穴は開けない","ペットのフタ・ラベルはプラへ"],
      en:["Hazardous items to the resource station","Empty spray cans; do not puncture","PET caps/labels go to plastic"],
      pt:["Itens perigosos à estação de recursos","Esvazie sprays; não fure","Tampas/rótulos de PET → plástico"],
      easy:["あぶない ごみは しげんステーションへ","スプレーは つかいきる・あなを あけない","ペットの ふたは プラへ"]} },

  { cat:"kinzoku", place:"station",
    desc:{ja:"金属製品。指定袋に入る大きさ。",
      en:"Metal products. Must fit in the city bag.",
      pt:"Produtos de metal. Deve caber na sacola oficial.",
      easy:"きんぞくの もの。ふくろに はいる おおきさ。"},
    items:{ja:["なべ・フライパン","やかん","金属ハンガー","傘（金属骨）","小型の金属製品"],
      en:["Pots/pans","Kettles","Metal hangers","Umbrellas (metal)","Small metal items"],
      pt:["Panelas/frigideiras","Chaleiras","Cabides de metal","Guarda-chuvas (metal)","Pequenos itens de metal"],
      easy:["なべ・フライパン","やかん","はんがー","かさ","ちいさい きんぞく"]},
    rules:{ja:["刃物は紙に包み「刃物」と表示","指定袋に入らない大きさは粗大ごみ"],
      en:["Wrap blades in paper, label 'blade'","If it doesn't fit the bag, it's oversized waste"],
      pt:["Embrulhe lâminas e marque 'lâmina'","Se não cabe na sacola, é volumoso"],
      easy:["はものは かみに つつむ","はいらない ものは そだいごみ"]} },

  { cat:"umeru", place:"station",
    desc:{ja:"陶磁器・ガラス・土砂など、燃えない小物。",
      en:"Ceramics, glass, soil—small non-burnable items.",
      pt:"Cerâmica, vidro, terra—pequenos não queimáveis.",
      easy:"とうき・ガラス・つち など、もえない ちいさい もの。"},
    items:{ja:["茶碗・皿（陶磁器）","ガラスコップ","鏡","植木鉢（陶器）","少量の土・砂・石"],
      en:["Bowls/dishes (ceramic)","Glass cups","Mirrors","Flower pots (ceramic)","Small soil/sand/stone"],
      pt:["Tigelas/pratos (cerâmica)","Copos de vidro","Espelhos","Vasos (cerâmica)","Pouca terra/areia/pedra"],
      easy:["ちゃわん・さら","ガラスの コップ","かがみ","うえきばち","すこしの つち・すな"]},
    rules:{ja:["割れ物は紙に包み「キケン」と表示"],
      en:["Wrap breakables in paper, label 'danger'"],
      pt:["Embrulhe frágeis e marque 'perigo'"],
      easy:["われものは かみに つつむ・「キケン」と かく"]} },

  // ---- 収集日カテゴリ外（分かりにくいポイント）----
  { key:"kosi", name:{ja:"古紙・古布（ダンボール等）", en:"Paper & cloth (cardboard)", pt:"Papel e tecido", easy:"かみ・ぬの（ダンボール）"},
    color:"#3a7cc0", icon:"📦", place:"recycle",
    desc:{ja:"ダンボール・新聞・雑誌・雑紙・紙パック・古布。ごみステーションでは回収しません。",
      en:"Cardboard, newspaper, magazines, cartons, cloth. NOT collected at waste stations.",
      pt:"Papelão, jornal, revistas, cartões, tecidos. NÃO coletado nas estações de lixo.",
      easy:"ダンボール・しんぶん・ざっし・かみパック・ふるぎ。ごみステーションでは あつめません。"},
    items:{ja:["ダンボール","新聞・チラシ","雑誌・本","雑紙","紙パック","古着・古布"],
      en:["Cardboard","Newspaper/flyers","Magazines/books","Misc paper","Cartons","Used clothes/cloth"],
      pt:["Papelão","Jornal/folhetos","Revistas/livros","Papéis diversos","Cartões","Roupas/tecidos"],
      easy:["ダンボール","しんぶん","ざっし・ほん","ざつがみ","かみパック","ふるぎ"]},
    rules:{ja:["リサイクルステーション（常設拠点）か集団回収へ","拠点は年中無休 10:00〜18:00（年末年始除く）","種類ごとにひもで縛る"],
      en:["To a recycling station (drop-off) or community collection","Open daily 10:00–18:00 (except year-end)","Tie by type with string"],
      pt:["À estação de reciclagem ou coleta comunitária","Aberto diário 10h–18h (exceto fim de ano)","Amarre por tipo com barbante"],
      easy:["リサイクルステーションか しゅうだんかいしゅうへ","まいにち 10〜18じ","しゅるいごとに ひもで しばる"]} },

  { key:"sodai", name:{ja:"粗大ごみ", en:"Oversized waste", pt:"Lixo volumoso", easy:"そだい ごみ"},
    color:"#7c5cbf", icon:"🛋️", place:"apply",
    desc:{ja:"市の指定袋に入らない大きさのもの（長さ4mまで）。",
      en:"Items too big for the city bag (up to 4 m long).",
      pt:"Itens que não cabem na sacola oficial (até 4 m).",
      easy:"ふくろに はいらない おおきい もの（ながさ 4mまで）。"},
    items:{ja:["家具・タンス","布団・マットレス","自転車","電子レンジ","カーペット"],
      en:["Furniture","Futons/mattresses","Bicycles","Microwaves","Carpets"],
      pt:["Móveis","Futons/colchões","Bicicletas","Micro-ondas","Tapetes"],
      easy:["かぐ","ふとん","じてんしゃ","でんしレンジ","カーペット"]},
    rules:{ja:["事前申込制・処理券が必要","家電4品目・パソコンは対象外（下記）"],
      en:["By prior request; fee sticker required","Excludes 4 appliances & PCs (see below)"],
      pt:["Sob pedido prévio; selo necessário","Exclui 4 eletrodomésticos e PCs (abaixo)"],
      easy:["さきに もうしこみ・けんが いる","かでん4つと パソコンは べつ"]} },

  { key:"kaden", name:{ja:"家電・収集しないもの", en:"Appliances / not collected", pt:"Eletrodomésticos / não coletado", easy:"かでん・あつめない もの"},
    color:"#c0563a", icon:"📺", place:"none",
    desc:{ja:"テレビ・エアコン・冷蔵庫・洗濯機・パソコンは市では収集しません。",
      en:"TVs, ACs, fridges, washers, PCs are not collected by the city.",
      pt:"TVs, ar-condicionado, geladeiras, máquinas de lavar e PCs não são coletados.",
      easy:"テレビ・エアコン・れいぞうこ・せんたくき・パソコンは あつめません。"},
    items:{ja:["テレビ","エアコン","冷蔵庫・冷凍庫","洗濯機・乾燥機","パソコン"],
      en:["TV","Air conditioner","Refrigerator","Washing machine","PC"],
      pt:["TV","Ar-condicionado","Geladeira","Máquina de lavar","Computador"],
      easy:["テレビ","エアコン","れいぞうこ","せんたくき","パソコン"]},
    rules:{ja:["家電4品目は販売店回収・指定引取場所へ","パソコンはメーカー回収・拠点回収へ"],
      en:["4 appliances: retailer or designated site","PCs: maker or drop-off recycling"],
      pt:["4 eletrodomésticos: loja ou local designado","PCs: fabricante ou reciclagem"],
      easy:["かでん4つは おみせへ","パソコンは メーカーへ"]} },
];
